/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_BandParameters_v1130_H_
#define	_BandParameters_v1130_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BandParameters_v1130__supportedCSI_Proc_r11 {
	BandParameters_v1130__supportedCSI_Proc_r11_n1	= 0,
	BandParameters_v1130__supportedCSI_Proc_r11_n3	= 1,
	BandParameters_v1130__supportedCSI_Proc_r11_n4	= 2
} e_BandParameters_v1130__supportedCSI_Proc_r11;

/* BandParameters-v1130 */
typedef struct BandParameters_v1130 {
	ENUMERATED_t	 supportedCSI_Proc_r11;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandParameters_v1130_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_supportedCSI_Proc_r11_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BandParameters_v1130;

#ifdef __cplusplus
}
#endif

#endif	/* _BandParameters_v1130_H_ */
#include <asn_internal.h>
