/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#include "CSI-Process-r11.h"

static int
alternativeCodebookEnabledFor4TXProc_r12_11_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
alternativeCodebookEnabledFor4TXProc_r12_11_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
alternativeCodebookEnabledFor4TXProc_r12_11_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
alternativeCodebookEnabledFor4TXProc_r12_11_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
alternativeCodebookEnabledFor4TXProc_r12_11_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
alternativeCodebookEnabledFor4TXProc_r12_11_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
alternativeCodebookEnabledFor4TXProc_r12_11_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
alternativeCodebookEnabledFor4TXProc_r12_11_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
alternativeCodebookEnabledFor4TXProc_r12_11_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	alternativeCodebookEnabledFor4TXProc_r12_11_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_setup_constraint_13(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 2)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_p_C_AndCBSRList_r11_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 2)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_cqi_ReportPeriodicProcId_r11_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_p_C_AndCBSRList_r11_constr_5 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_alternativeCodebookEnabledFor4TXProc_r12_constr_11 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_setup_constr_15 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_setup_constr_15 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_csi_IM_ConfigIdList_r12_constr_13 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_cqi_ReportAperiodicProc2_r12_constr_17 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_cqi_ReportAperiodicProc_v1310_constr_20 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_cqi_ReportAperiodicProc2_v1310_constr_23 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_p_C_AndCBSRList_r11_constr_5 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (SIZE(1..2)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_cqi_ReportPeriodicProcId_r11_constr_8 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_p_C_AndCBSRList_r11_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_P_C_AndCBSR_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_p_C_AndCBSRList_r11_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_p_C_AndCBSRList_r11_specs_5 = {
	sizeof(struct CSI_Process_r11__p_C_AndCBSRList_r11),
	offsetof(struct CSI_Process_r11__p_C_AndCBSRList_r11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_p_C_AndCBSRList_r11_5 = {
	"p-C-AndCBSRList-r11",
	"p-C-AndCBSRList-r11",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_p_C_AndCBSRList_r11_tags_5,
	sizeof(asn_DEF_p_C_AndCBSRList_r11_tags_5)
		/sizeof(asn_DEF_p_C_AndCBSRList_r11_tags_5[0]) - 1, /* 1 */
	asn_DEF_p_C_AndCBSRList_r11_tags_5,	/* Same as above */
	sizeof(asn_DEF_p_C_AndCBSRList_r11_tags_5)
		/sizeof(asn_DEF_p_C_AndCBSRList_r11_tags_5[0]), /* 2 */
	&asn_PER_type_p_C_AndCBSRList_r11_constr_5,
	asn_MBR_p_C_AndCBSRList_r11_5,
	1,	/* Single element */
	&asn_SPC_p_C_AndCBSRList_r11_specs_5	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_alternativeCodebookEnabledFor4TXProc_r12_value2enum_11[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_alternativeCodebookEnabledFor4TXProc_r12_enum2value_11[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_alternativeCodebookEnabledFor4TXProc_r12_specs_11 = {
	asn_MAP_alternativeCodebookEnabledFor4TXProc_r12_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_alternativeCodebookEnabledFor4TXProc_r12_enum2value_11,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_11 = {
	"alternativeCodebookEnabledFor4TXProc-r12",
	"alternativeCodebookEnabledFor4TXProc-r12",
	alternativeCodebookEnabledFor4TXProc_r12_11_free,
	alternativeCodebookEnabledFor4TXProc_r12_11_print,
	alternativeCodebookEnabledFor4TXProc_r12_11_constraint,
	alternativeCodebookEnabledFor4TXProc_r12_11_decode_ber,
	alternativeCodebookEnabledFor4TXProc_r12_11_encode_der,
	alternativeCodebookEnabledFor4TXProc_r12_11_decode_xer,
	alternativeCodebookEnabledFor4TXProc_r12_11_encode_xer,
	alternativeCodebookEnabledFor4TXProc_r12_11_decode_uper,
	alternativeCodebookEnabledFor4TXProc_r12_11_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11,
	sizeof(asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11)
		/sizeof(asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11[0]) - 1, /* 1 */
	asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11,	/* Same as above */
	sizeof(asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11)
		/sizeof(asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_tags_11[0]), /* 2 */
	&asn_PER_type_alternativeCodebookEnabledFor4TXProc_r12_constr_11,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_alternativeCodebookEnabledFor4TXProc_r12_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CSI_IM_ConfigId_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_setup_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_setup_specs_15 = {
	sizeof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12__setup),
	offsetof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12__setup, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_15 = {
	"setup",
	"setup",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_15,
	sizeof(asn_DEF_setup_tags_15)
		/sizeof(asn_DEF_setup_tags_15[0]) - 1, /* 1 */
	asn_DEF_setup_tags_15,	/* Same as above */
	sizeof(asn_DEF_setup_tags_15)
		/sizeof(asn_DEF_setup_tags_15[0]), /* 2 */
	&asn_PER_type_setup_constr_15,
	asn_MBR_setup_15,
	1,	/* Single element */
	&asn_SPC_setup_specs_15	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_csi_IM_ConfigIdList_r12_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_15,
		memb_setup_constraint_13,
		&asn_PER_memb_setup_constr_15,
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_csi_IM_ConfigIdList_r12_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_csi_IM_ConfigIdList_r12_specs_13 = {
	sizeof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12),
	offsetof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12, _asn_ctx),
	offsetof(struct CSI_Process_r11__csi_IM_ConfigIdList_r12, present),
	sizeof(((struct CSI_Process_r11__csi_IM_ConfigIdList_r12 *)0)->present),
	asn_MAP_csi_IM_ConfigIdList_r12_tag2el_13,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csi_IM_ConfigIdList_r12_13 = {
	"csi-IM-ConfigIdList-r12",
	"csi-IM-ConfigIdList-r12",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_csi_IM_ConfigIdList_r12_constr_13,
	asn_MBR_csi_IM_ConfigIdList_r12_13,
	2,	/* Elements count */
	&asn_SPC_csi_IM_ConfigIdList_r12_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_cqi_ReportAperiodicProc2_r12_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_r12, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_r12, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportAperiodicProc_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_cqi_ReportAperiodicProc2_r12_tag2el_17[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_cqi_ReportAperiodicProc2_r12_specs_17 = {
	sizeof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_r12),
	offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_r12, _asn_ctx),
	offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_r12, present),
	sizeof(((struct CSI_Process_r11__cqi_ReportAperiodicProc2_r12 *)0)->present),
	asn_MAP_cqi_ReportAperiodicProc2_r12_tag2el_17,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cqi_ReportAperiodicProc2_r12_17 = {
	"cqi-ReportAperiodicProc2-r12",
	"cqi-ReportAperiodicProc2-r12",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_cqi_ReportAperiodicProc2_r12_constr_17,
	asn_MBR_cqi_ReportAperiodicProc2_r12_17,
	2,	/* Elements count */
	&asn_SPC_cqi_ReportAperiodicProc2_r12_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_cqi_ReportAperiodicProc_v1310_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc_v1310, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc_v1310, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportAperiodicProc_v1310,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_cqi_ReportAperiodicProc_v1310_tag2el_20[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_cqi_ReportAperiodicProc_v1310_specs_20 = {
	sizeof(struct CSI_Process_r11__cqi_ReportAperiodicProc_v1310),
	offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc_v1310, _asn_ctx),
	offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc_v1310, present),
	sizeof(((struct CSI_Process_r11__cqi_ReportAperiodicProc_v1310 *)0)->present),
	asn_MAP_cqi_ReportAperiodicProc_v1310_tag2el_20,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cqi_ReportAperiodicProc_v1310_20 = {
	"cqi-ReportAperiodicProc-v1310",
	"cqi-ReportAperiodicProc-v1310",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_cqi_ReportAperiodicProc_v1310_constr_20,
	asn_MBR_cqi_ReportAperiodicProc_v1310_20,
	2,	/* Elements count */
	&asn_SPC_cqi_ReportAperiodicProc_v1310_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_cqi_ReportAperiodicProc2_v1310_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_v1310, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_v1310, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportAperiodicProc_v1310,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_cqi_ReportAperiodicProc2_v1310_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_cqi_ReportAperiodicProc2_v1310_specs_23 = {
	sizeof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_v1310),
	offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_v1310, _asn_ctx),
	offsetof(struct CSI_Process_r11__cqi_ReportAperiodicProc2_v1310, present),
	sizeof(((struct CSI_Process_r11__cqi_ReportAperiodicProc2_v1310 *)0)->present),
	asn_MAP_cqi_ReportAperiodicProc2_v1310_tag2el_23,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cqi_ReportAperiodicProc2_v1310_23 = {
	"cqi-ReportAperiodicProc2-v1310",
	"cqi-ReportAperiodicProc2-v1310",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_cqi_ReportAperiodicProc2_v1310_constr_23,
	asn_MBR_cqi_ReportAperiodicProc2_v1310_23,
	2,	/* Elements count */
	&asn_SPC_cqi_ReportAperiodicProc2_v1310_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_CSI_Process_r11_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11, csi_ProcessId_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_ProcessId_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-ProcessId-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11, csi_RS_ConfigNZPId_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigNZPId_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-RS-ConfigNZPId-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11, csi_IM_ConfigId_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSI_IM_ConfigId_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-IM-ConfigId-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CSI_Process_r11, p_C_AndCBSRList_r11),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_p_C_AndCBSRList_r11_5,
		memb_p_C_AndCBSRList_r11_constraint_1,
		&asn_PER_memb_p_C_AndCBSRList_r11_constr_5,
		0,
		"p-C-AndCBSRList-r11"
		},
	{ ATF_POINTER, 9, offsetof(struct CSI_Process_r11, cqi_ReportBothProc_r11),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportBothProc_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cqi-ReportBothProc-r11"
		},
	{ ATF_POINTER, 8, offsetof(struct CSI_Process_r11, cqi_ReportPeriodicProcId_r11),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_cqi_ReportPeriodicProcId_r11_constraint_1,
		&asn_PER_memb_cqi_ReportPeriodicProcId_r11_constr_8,
		0,
		"cqi-ReportPeriodicProcId-r11"
		},
	{ ATF_POINTER, 7, offsetof(struct CSI_Process_r11, cqi_ReportAperiodicProc_r11),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CQI_ReportAperiodicProc_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cqi-ReportAperiodicProc-r11"
		},
	{ ATF_POINTER, 6, offsetof(struct CSI_Process_r11, alternativeCodebookEnabledFor4TXProc_r12),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"alternativeCodebookEnabledFor4TXProc-r12"
		},
	{ ATF_POINTER, 5, offsetof(struct CSI_Process_r11, csi_IM_ConfigIdList_r12),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_csi_IM_ConfigIdList_r12_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csi-IM-ConfigIdList-r12"
		},
	{ ATF_POINTER, 4, offsetof(struct CSI_Process_r11, cqi_ReportAperiodicProc2_r12),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_cqi_ReportAperiodicProc2_r12_17,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cqi-ReportAperiodicProc2-r12"
		},
	{ ATF_POINTER, 3, offsetof(struct CSI_Process_r11, cqi_ReportAperiodicProc_v1310),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_cqi_ReportAperiodicProc_v1310_20,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cqi-ReportAperiodicProc-v1310"
		},
	{ ATF_POINTER, 2, offsetof(struct CSI_Process_r11, cqi_ReportAperiodicProc2_v1310),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_cqi_ReportAperiodicProc2_v1310_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cqi-ReportAperiodicProc2-v1310"
		},
	{ ATF_POINTER, 1, offsetof(struct CSI_Process_r11, eMIMO_Type_r13),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CSI_RS_ConfigEMIMO_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eMIMO-Type-r13"
		},
};
static int asn_MAP_CSI_Process_r11_oms_1[] = { 4, 5, 6, 7, 8, 9, 10, 11, 12 };
static ber_tlv_tag_t asn_DEF_CSI_Process_r11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_CSI_Process_r11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* csi-ProcessId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* csi-RS-ConfigNZPId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* csi-IM-ConfigId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* p-C-AndCBSRList-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* cqi-ReportBothProc-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* cqi-ReportPeriodicProcId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* cqi-ReportAperiodicProc-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* alternativeCodebookEnabledFor4TXProc-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* csi-IM-ConfigIdList-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* cqi-ReportAperiodicProc2-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* cqi-ReportAperiodicProc-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* cqi-ReportAperiodicProc2-v1310 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 } /* eMIMO-Type-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_CSI_Process_r11_specs_1 = {
	sizeof(struct CSI_Process_r11),
	offsetof(struct CSI_Process_r11, _asn_ctx),
	asn_MAP_CSI_Process_r11_tag2el_1,
	13,	/* Count of tags in the map */
	asn_MAP_CSI_Process_r11_oms_1,	/* Optional members */
	3, 6,	/* Root/Additions */
	6,	/* Start extensions */
	14	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_CSI_Process_r11 = {
	"CSI-Process-r11",
	"CSI-Process-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_CSI_Process_r11_tags_1,
	sizeof(asn_DEF_CSI_Process_r11_tags_1)
		/sizeof(asn_DEF_CSI_Process_r11_tags_1[0]), /* 1 */
	asn_DEF_CSI_Process_r11_tags_1,	/* Same as above */
	sizeof(asn_DEF_CSI_Process_r11_tags_1)
		/sizeof(asn_DEF_CSI_Process_r11_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_CSI_Process_r11_1,
	13,	/* Elements count */
	&asn_SPC_CSI_Process_r11_specs_1	/* Additional specs */
};

