/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_CSI_RS_ConfigBeamformed_r13_H_
#define	_CSI_RS_ConfigBeamformed_r13_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include "CSI-RS-ConfigNZPId-r13.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "CSI-IM-ConfigId-r13.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CSI_RS_ConfigBeamformed_r13__alternativeCodebookEnabledBeamformed_r13 {
	CSI_RS_ConfigBeamformed_r13__alternativeCodebookEnabledBeamformed_r13_true	= 0
} e_CSI_RS_ConfigBeamformed_r13__alternativeCodebookEnabledBeamformed_r13;
typedef enum CSI_RS_ConfigBeamformed_r13__channelMeasRestriction_r13 {
	CSI_RS_ConfigBeamformed_r13__channelMeasRestriction_r13_on	= 0
} e_CSI_RS_ConfigBeamformed_r13__channelMeasRestriction_r13;

/* Forward declarations */
struct P_C_AndCBSR_PerResourceConfig_r13;

/* CSI-RS-ConfigBeamformed-r13 */
typedef struct CSI_RS_ConfigBeamformed_r13 {
	struct CSI_RS_ConfigBeamformed_r13__csi_RS_ConfigNZPIdListExt_r13 {
		A_SEQUENCE_OF(CSI_RS_ConfigNZPId_r13_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *csi_RS_ConfigNZPIdListExt_r13;
	struct CSI_RS_ConfigBeamformed_r13__csi_IM_ConfigIdList_r13 {
		A_SEQUENCE_OF(CSI_IM_ConfigId_r13_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *csi_IM_ConfigIdList_r13;
	struct CSI_RS_ConfigBeamformed_r13__p_C_AndCBSR_PerResourceConfigList_r13 {
		A_SEQUENCE_OF(struct P_C_AndCBSR_PerResourceConfig_r13) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *p_C_AndCBSR_PerResourceConfigList_r13;
	struct CSI_RS_ConfigBeamformed_r13__ace_For4Tx_PerResourceConfigList_r13 {
		A_SEQUENCE_OF(BOOLEAN_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ace_For4Tx_PerResourceConfigList_r13;
	ENUMERATED_t	*alternativeCodebookEnabledBeamformed_r13	/* OPTIONAL */;
	ENUMERATED_t	*channelMeasRestriction_r13	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSI_RS_ConfigBeamformed_r13_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_alternativeCodebookEnabledBeamformed_r13_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_channelMeasRestriction_r13_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CSI_RS_ConfigBeamformed_r13;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "P-C-AndCBSR-PerResourceConfig-r13.h"

#endif	/* _CSI_RS_ConfigBeamformed_r13_H_ */
#include <asn_internal.h>
