/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_DeltaTxD_OffsetListPUCCH_v1130_H_
#define	_DeltaTxD_OffsetListPUCCH_v1130_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeltaTxD_OffsetListPUCCH_v1130__deltaTxD_OffsetPUCCH_Format1bCS_r11 {
	DeltaTxD_OffsetListPUCCH_v1130__deltaTxD_OffsetPUCCH_Format1bCS_r11_dB0	= 0,
	DeltaTxD_OffsetListPUCCH_v1130__deltaTxD_OffsetPUCCH_Format1bCS_r11_dB_1	= 1
} e_DeltaTxD_OffsetListPUCCH_v1130__deltaTxD_OffsetPUCCH_Format1bCS_r11;

/* DeltaTxD-OffsetListPUCCH-v1130 */
typedef struct DeltaTxD_OffsetListPUCCH_v1130 {
	ENUMERATED_t	 deltaTxD_OffsetPUCCH_Format1bCS_r11;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeltaTxD_OffsetListPUCCH_v1130_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_deltaTxD_OffsetPUCCH_Format1bCS_r11_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DeltaTxD_OffsetListPUCCH_v1130;

#ifdef __cplusplus
}
#endif

#endif	/* _DeltaTxD_OffsetListPUCCH_v1130_H_ */
#include <asn_internal.h>
