/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_DRB_InfoSCG_r12_H_
#define	_DRB_InfoSCG_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "DRB-Identity.h"
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DRB_InfoSCG_r12__drb_Type_r12 {
	DRB_InfoSCG_r12__drb_Type_r12_split	= 0,
	DRB_InfoSCG_r12__drb_Type_r12_scg	= 1
} e_DRB_InfoSCG_r12__drb_Type_r12;

/* DRB-InfoSCG-r12 */
typedef struct DRB_InfoSCG_r12 {
	long	*eps_BearerIdentity_r12	/* OPTIONAL */;
	DRB_Identity_t	 drb_Identity_r12;
	ENUMERATED_t	*drb_Type_r12	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_InfoSCG_r12_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_drb_Type_r12_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_DRB_InfoSCG_r12;

#ifdef __cplusplus
}
#endif

#endif	/* _DRB_InfoSCG_r12_H_ */
#include <asn_internal.h>
