/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_HandoverPreparationInformation_v1250_IEs_H_
#define	_HandoverPreparationInformation_v1250_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueEUTRA-r9.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AS_Config_v1250;

/* HandoverPreparationInformation-v1250-IEs */
typedef struct HandoverPreparationInformation_v1250_IEs {
	ARFCN_ValueEUTRA_r9_t	*ue_SupportedEARFCN_r12	/* OPTIONAL */;
	struct AS_Config_v1250	*as_Config_v1250	/* OPTIONAL */;
	struct HandoverPreparationInformation_v1250_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverPreparationInformation_v1250_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverPreparationInformation_v1250_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AS-Config-v1250.h"

#endif	/* _HandoverPreparationInformation_v1250_IEs_H_ */
#include <asn_internal.h>
