/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_IRAT_ParametersCDMA2000_1XRTT_v920_H_
#define	_IRAT_ParametersCDMA2000_1XRTT_v920_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IRAT_ParametersCDMA2000_1XRTT_v920__e_CSFB_1XRTT_r9 {
	IRAT_ParametersCDMA2000_1XRTT_v920__e_CSFB_1XRTT_r9_supported	= 0
} e_IRAT_ParametersCDMA2000_1XRTT_v920__e_CSFB_1XRTT_r9;
typedef enum IRAT_ParametersCDMA2000_1XRTT_v920__e_CSFB_ConcPS_Mob1XRTT_r9 {
	IRAT_ParametersCDMA2000_1XRTT_v920__e_CSFB_ConcPS_Mob1XRTT_r9_supported	= 0
} e_IRAT_ParametersCDMA2000_1XRTT_v920__e_CSFB_ConcPS_Mob1XRTT_r9;

/* IRAT-ParametersCDMA2000-1XRTT-v920 */
typedef struct IRAT_ParametersCDMA2000_1XRTT_v920 {
	ENUMERATED_t	 e_CSFB_1XRTT_r9;
	ENUMERATED_t	*e_CSFB_ConcPS_Mob1XRTT_r9	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IRAT_ParametersCDMA2000_1XRTT_v920_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_e_CSFB_1XRTT_r9_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_e_CSFB_ConcPS_Mob1XRTT_r9_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IRAT_ParametersCDMA2000_1XRTT_v920;

#ifdef __cplusplus
}
#endif

#endif	/* _IRAT_ParametersCDMA2000_1XRTT_v920_H_ */
#include <asn_internal.h>
