/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_MeasResult2EUTRA_v1250_H_
#define	_MeasResult2EUTRA_v1250_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RSRQ_Type_r12;

/* MeasResult2EUTRA-v1250 */
typedef struct MeasResult2EUTRA_v1250 {
	struct RSRQ_Type_r12	*rsrq_Type_r12	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResult2EUTRA_v1250_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResult2EUTRA_v1250;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RSRQ-Type-r12.h"

#endif	/* _MeasResult2EUTRA_v1250_H_ */
#include <asn_internal.h>
