/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_NumberOfPreamblesSent_r11_H_
#define	_NumberOfPreamblesSent_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumberOfPreamblesSent-r11 */
typedef long	 NumberOfPreamblesSent_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberOfPreamblesSent_r11;
asn_struct_free_f NumberOfPreamblesSent_r11_free;
asn_struct_print_f NumberOfPreamblesSent_r11_print;
asn_constr_check_f NumberOfPreamblesSent_r11_constraint;
ber_type_decoder_f NumberOfPreamblesSent_r11_decode_ber;
der_type_encoder_f NumberOfPreamblesSent_r11_encode_der;
xer_type_decoder_f NumberOfPreamblesSent_r11_decode_xer;
xer_type_encoder_f NumberOfPreamblesSent_r11_encode_xer;
per_type_decoder_f NumberOfPreamblesSent_r11_decode_uper;
per_type_encoder_f NumberOfPreamblesSent_r11_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfPreamblesSent_r11_H_ */
#include <asn_internal.h>
