/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 */

#include "pdu_collection.h"

extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_DL_SCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_DL_SCH_Message_BR;
extern struct asn_TYPE_descriptor_s asn_DEF_MCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_PCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_SC_MCCH_Message_r13;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCConnectionReconfiguration_v8m0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCConnectionRelease_v9e0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType1_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UEInformationResponse_v9e0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType2_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType3_v10j0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType5_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType6_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_EUTRA_Capability;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_EUTRA_Capability_v9a0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_EUTRA_Capability_v10j0_IEs;
//extern struct asn_TYPE_descriptor_s asn_DEF_LAA_parameters_r13;
extern struct asn_TYPE_descriptor_s asn_DEF_SL_TxPoolIdentity_r13;
extern struct asn_TYPE_descriptor_s asn_DEF_SBCCH_SL_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_VarConnEstFailReport_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasConfig_r10;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasConfig_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasConfig_r12;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasReport_r10;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasReport_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasConfig;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasReportList;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasReportList_r12;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMobilityHistoryReport_r12;
extern struct asn_TYPE_descriptor_s asn_DEF_VarRLF_Report_r10;
extern struct asn_TYPE_descriptor_s asn_DEF_VarRLF_Report_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarShortMAC_Input;
extern struct asn_TYPE_descriptor_s asn_DEF_VarWLAN_MobilityConfig;
extern struct asn_TYPE_descriptor_s asn_DEF_VarWLAN_Status_r13;
extern struct asn_TYPE_descriptor_s asn_DEF_SL_Preconfiguration_r12;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverPreparationInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverPreparationInformation_v9j0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SCG_ConfigInfo_r12;
extern struct asn_TYPE_descriptor_s asn_DEF_UEPagingCoverageInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioAccessCapabilityInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioPagingInformation;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module EUTRA-RRC-Definitions in /home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn */
	&asn_DEF_BCCH_BCH_Message,	
	&asn_DEF_BCCH_DL_SCH_Message,	
	&asn_DEF_BCCH_DL_SCH_Message_BR,	
	&asn_DEF_MCCH_Message,	
	&asn_DEF_PCCH_Message,	
	&asn_DEF_DL_CCCH_Message,	
	&asn_DEF_DL_DCCH_Message,	
	&asn_DEF_UL_CCCH_Message,	
	&asn_DEF_UL_DCCH_Message,	
	&asn_DEF_SC_MCCH_Message_r13,	
	&asn_DEF_RRCConnectionReconfiguration_v8m0_IEs,	
	&asn_DEF_RRCConnectionRelease_v9e0_IEs,	
	&asn_DEF_SystemInformationBlockType1_v8h0_IEs,	
	&asn_DEF_UEInformationResponse_v9e0_IEs,	
	&asn_DEF_SystemInformationBlockType2_v8h0_IEs,	
	&asn_DEF_SystemInformationBlockType3_v10j0_IEs,	
	&asn_DEF_SystemInformationBlockType5_v8h0_IEs,	
	&asn_DEF_SystemInformationBlockType6_v8h0_IEs,	
	&asn_DEF_UE_EUTRA_Capability,	
	&asn_DEF_UE_EUTRA_Capability_v9a0_IEs,	
	&asn_DEF_UE_EUTRA_Capability_v10j0_IEs,	
	/*&asn_DEF_LAA_parameters_r13,*/	
	&asn_DEF_SL_TxPoolIdentity_r13,	
	/* From module PC5-RRC-Definitions in /home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn */
	&asn_DEF_SBCCH_SL_BCH_Message,	
	/* From module EUTRA-UE-Variables in /home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn */
	&asn_DEF_VarConnEstFailReport_r11,	
	&asn_DEF_VarLogMeasConfig_r10,	
	&asn_DEF_VarLogMeasConfig_r11,	
	&asn_DEF_VarLogMeasConfig_r12,	
	&asn_DEF_VarLogMeasReport_r10,	
	&asn_DEF_VarLogMeasReport_r11,	
	&asn_DEF_VarMeasConfig,	
	&asn_DEF_VarMeasReportList,	
	&asn_DEF_VarMeasReportList_r12,	
	&asn_DEF_VarMobilityHistoryReport_r12,	
	&asn_DEF_VarRLF_Report_r10,	
	&asn_DEF_VarRLF_Report_r11,	
	&asn_DEF_VarShortMAC_Input,	
	&asn_DEF_VarWLAN_MobilityConfig,	
	&asn_DEF_VarWLAN_Status_r13,	
	/* From module EUTRA-Sidelink-Preconf in /home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn */
	&asn_DEF_SL_Preconfiguration_r12,	
	/* From module EUTRA-InterNodeDefinitions in /home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn */
	&asn_DEF_HandoverCommand,	
	&asn_DEF_HandoverPreparationInformation,	
	&asn_DEF_HandoverPreparationInformation_v9j0_IEs,	
	&asn_DEF_SCG_ConfigInfo_r12,	
	&asn_DEF_UEPagingCoverageInformation,	
	&asn_DEF_UERadioAccessCapabilityInformation,	
	&asn_DEF_UERadioPagingInformation,	
	0
};
