/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_PRACH_ConfigSCell_r10_H_
#define	_PRACH_ConfigSCell_r10_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PRACH-ConfigSCell-r10 */
typedef struct PRACH_ConfigSCell_r10 {
	long	 prach_ConfigIndex_r10;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PRACH_ConfigSCell_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PRACH_ConfigSCell_r10;

#ifdef __cplusplus
}
#endif

#endif	/* _PRACH_ConfigSCell_r10_H_ */
#include <asn_internal.h>
