/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_PUSCH_ConfigDedicated_H_
#define	_PUSCH_ConfigDedicated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PUSCH-ConfigDedicated */
typedef struct PUSCH_ConfigDedicated {
	long	 betaOffset_ACK_Index;
	long	 betaOffset_RI_Index;
	long	 betaOffset_CQI_Index;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUSCH_ConfigDedicated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUSCH_ConfigDedicated;

#ifdef __cplusplus
}
#endif

#endif	/* _PUSCH_ConfigDedicated_H_ */
#include <asn_internal.h>
