/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_RF_Parameters_v10j0_H_
#define	_RF_Parameters_v10j0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RF_Parameters_v10j0__multiNS_Pmax_r10 {
	RF_Parameters_v10j0__multiNS_Pmax_r10_supported	= 0
} e_RF_Parameters_v10j0__multiNS_Pmax_r10;

/* RF-Parameters-v10j0 */
typedef struct RF_Parameters_v10j0 {
	ENUMERATED_t	*multiNS_Pmax_r10	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RF_Parameters_v10j0_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_multiNS_Pmax_r10_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RF_Parameters_v10j0;

#ifdef __cplusplus
}
#endif

#endif	/* _RF_Parameters_v10j0_H_ */
#include <asn_internal.h>
