/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_RRCConnectionRelease_r8_IEs_H_
#define	_RRCConnectionRelease_r8_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReleaseCause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RedirectedCarrierInfo;
struct IdleModeMobilityControlInfo;
struct RRCConnectionRelease_v890_IEs;

/* RRCConnectionRelease-r8-IEs */
typedef struct RRCConnectionRelease_r8_IEs {
	ReleaseCause_t	 releaseCause;
	struct RedirectedCarrierInfo	*redirectedCarrierInfo	/* OPTIONAL */;
	struct IdleModeMobilityControlInfo	*idleModeMobilityControlInfo	/* OPTIONAL */;
	struct RRCConnectionRelease_v890_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionRelease_r8_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionRelease_r8_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RedirectedCarrierInfo.h"
#include "IdleModeMobilityControlInfo.h"
#include "RRCConnectionRelease-v890-IEs.h"

#endif	/* _RRCConnectionRelease_r8_IEs_H_ */
#include <asn_internal.h>
