/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_RRCConnectionReconfigurationComplete_v1020_IEs_H_
#define	_RRCConnectionReconfigurationComplete_v1020_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionReconfigurationComplete_v1020_IEs__rlf_InfoAvailable_r10 {
	RRCConnectionReconfigurationComplete_v1020_IEs__rlf_InfoAvailable_r10_true	= 0
} e_RRCConnectionReconfigurationComplete_v1020_IEs__rlf_InfoAvailable_r10;
typedef enum RRCConnectionReconfigurationComplete_v1020_IEs__logMeasAvailable_r10 {
	RRCConnectionReconfigurationComplete_v1020_IEs__logMeasAvailable_r10_true	= 0
} e_RRCConnectionReconfigurationComplete_v1020_IEs__logMeasAvailable_r10;

/* Forward declarations */
struct RRCConnectionReconfigurationComplete_v1130_IEs;

/* RRCConnectionReconfigurationComplete-v1020-IEs */
typedef struct RRCConnectionReconfigurationComplete_v1020_IEs {
	ENUMERATED_t	*rlf_InfoAvailable_r10	/* OPTIONAL */;
	ENUMERATED_t	*logMeasAvailable_r10	/* OPTIONAL */;
	struct RRCConnectionReconfigurationComplete_v1130_IEs	*nonCriticalExtension	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReconfigurationComplete_v1020_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rlf_InfoAvailable_r10_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_logMeasAvailable_r10_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReconfigurationComplete_v1020_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RRCConnectionReconfigurationComplete-v1130-IEs.h"

#endif	/* _RRCConnectionReconfigurationComplete_v1020_IEs_H_ */
#include <asn_internal.h>
