/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_RRCConnectionReconfiguration_v1310_IEs_H_
#define	_RRCConnectionReconfiguration_v1310_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "WLAN-Id-List-r12.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_PR {
	RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_PR_NOTHING,	/* No components present */
	RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_PR_release,
	RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_PR_setup
} RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_PR;
typedef enum RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_PR {
	RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_PR_NOTHING,	/* No components present */
	RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_PR_steerToWLAN_r13,
	RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_PR_steerToLTE_r13
} RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_PR;

/* Forward declarations */
struct SCellToReleaseListExt_r13;
struct SCellToAddModListExt_r13;
struct LWA_Configuration_r13;
struct LWIP_Configuration_r13;

/* RRCConnectionReconfiguration-v1310-IEs */
typedef struct RRCConnectionReconfiguration_v1310_IEs {
	struct SCellToReleaseListExt_r13	*sCellToReleaseListExt_r13	/* OPTIONAL */;
	struct SCellToAddModListExt_r13	*sCellToAddModListExt_r13	/* OPTIONAL */;
	struct LWA_Configuration_r13	*lwa_Configuration_r13	/* OPTIONAL */;
	struct LWIP_Configuration_r13	*lwip_Configuration_r13	/* OPTIONAL */;
	struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13 {
		RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_PR present;
		union RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13_u {
			NULL_t	 release;
			struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup {
				struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command {
					RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_PR present;
					union RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command_u {
						WLAN_Id_List_r12_t	 steerToWLAN_r13;
						NULL_t	 steerToLTE_r13;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} command;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} setup;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *steeringCommandWLAN_r13;
	struct RRCConnectionReconfiguration_v1310_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReconfiguration_v1310_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReconfiguration_v1310_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SCellToReleaseListExt-r13.h"
#include "SCellToAddModListExt-r13.h"
#include "LWA-Configuration-r13.h"
#include "LWIP-Configuration-r13.h"

#endif	/* _RRCConnectionReconfiguration_v1310_IEs_H_ */
#include <asn_internal.h>
