/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#include "RRCConnectionReconfiguration-v1310-IEs.h"

static asn_per_constraints_t asn_PER_type_command_constr_9 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_steeringCommandWLAN_r13_constr_6 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_command_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command, choice.steerToWLAN_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_WLAN_Id_List_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"steerToWLAN-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command, choice.steerToLTE_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"steerToLTE-r13"
		},
};
static asn_TYPE_tag2member_t asn_MAP_command_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* steerToWLAN-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* steerToLTE-r13 */
};
static asn_CHOICE_specifics_t asn_SPC_command_specs_9 = {
	sizeof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command, _asn_ctx),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command, present),
	sizeof(((struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup__command *)0)->present),
	asn_MAP_command_tag2el_9,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_command_9 = {
	"command",
	"command",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_command_constr_9,
	asn_MBR_command_9,
	2,	/* Elements count */
	&asn_SPC_command_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_setup_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup, command),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_command_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"command"
		},
};
static ber_tlv_tag_t asn_DEF_setup_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_setup_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* command */
};
static asn_SEQUENCE_specifics_t asn_SPC_setup_specs_8 = {
	sizeof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13__setup, _asn_ctx),
	asn_MAP_setup_tag2el_8,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* Start extensions */
	2	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setup_8 = {
	"setup",
	"setup",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_setup_tags_8,
	sizeof(asn_DEF_setup_tags_8)
		/sizeof(asn_DEF_setup_tags_8[0]) - 1, /* 1 */
	asn_DEF_setup_tags_8,	/* Same as above */
	sizeof(asn_DEF_setup_tags_8)
		/sizeof(asn_DEF_setup_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_setup_8,
	1,	/* Elements count */
	&asn_SPC_setup_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_steeringCommandWLAN_r13_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13, choice.release),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13, choice.setup),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_setup_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"setup"
		},
};
static asn_TYPE_tag2member_t asn_MAP_steeringCommandWLAN_r13_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* release */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* setup */
};
static asn_CHOICE_specifics_t asn_SPC_steeringCommandWLAN_r13_specs_6 = {
	sizeof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13, _asn_ctx),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13, present),
	sizeof(((struct RRCConnectionReconfiguration_v1310_IEs__steeringCommandWLAN_r13 *)0)->present),
	asn_MAP_steeringCommandWLAN_r13_tag2el_6,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_steeringCommandWLAN_r13_6 = {
	"steeringCommandWLAN-r13",
	"steeringCommandWLAN-r13",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_steeringCommandWLAN_r13_constr_6,
	asn_MBR_steeringCommandWLAN_r13_6,
	2,	/* Elements count */
	&asn_SPC_steeringCommandWLAN_r13_specs_6	/* Additional specs */
};

static ber_tlv_tag_t asn_DEF_nonCriticalExtension_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtension_specs_13 = {
	sizeof(struct RRCConnectionReconfiguration_v1310_IEs__nonCriticalExtension),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs__nonCriticalExtension, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtension_13 = {
	"nonCriticalExtension",
	"nonCriticalExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtension_tags_13,
	sizeof(asn_DEF_nonCriticalExtension_tags_13)
		/sizeof(asn_DEF_nonCriticalExtension_tags_13[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtension_tags_13,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtension_tags_13)
		/sizeof(asn_DEF_nonCriticalExtension_tags_13[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtension_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRCConnectionReconfiguration_v1310_IEs_1[] = {
	{ ATF_POINTER, 6, offsetof(struct RRCConnectionReconfiguration_v1310_IEs, sCellToReleaseListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToReleaseListExt_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sCellToReleaseListExt-r13"
		},
	{ ATF_POINTER, 5, offsetof(struct RRCConnectionReconfiguration_v1310_IEs, sCellToAddModListExt_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SCellToAddModListExt_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sCellToAddModListExt-r13"
		},
	{ ATF_POINTER, 4, offsetof(struct RRCConnectionReconfiguration_v1310_IEs, lwa_Configuration_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LWA_Configuration_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lwa-Configuration-r13"
		},
	{ ATF_POINTER, 3, offsetof(struct RRCConnectionReconfiguration_v1310_IEs, lwip_Configuration_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_LWIP_Configuration_r13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"lwip-Configuration-r13"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCConnectionReconfiguration_v1310_IEs, steeringCommandWLAN_r13),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_steeringCommandWLAN_r13_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"steeringCommandWLAN-r13"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionReconfiguration_v1310_IEs, nonCriticalExtension),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_nonCriticalExtension_13,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtension"
		},
};
static int asn_MAP_RRCConnectionReconfiguration_v1310_IEs_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static ber_tlv_tag_t asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RRCConnectionReconfiguration_v1310_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sCellToReleaseListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sCellToAddModListExt-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* lwa-Configuration-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* lwip-Configuration-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* steeringCommandWLAN-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* nonCriticalExtension */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionReconfiguration_v1310_IEs_specs_1 = {
	sizeof(struct RRCConnectionReconfiguration_v1310_IEs),
	offsetof(struct RRCConnectionReconfiguration_v1310_IEs, _asn_ctx),
	asn_MAP_RRCConnectionReconfiguration_v1310_IEs_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_RRCConnectionReconfiguration_v1310_IEs_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RRCConnectionReconfiguration_v1310_IEs = {
	"RRCConnectionReconfiguration-v1310-IEs",
	"RRCConnectionReconfiguration-v1310-IEs",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1,
	sizeof(asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1)
		/sizeof(asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1[0]), /* 1 */
	asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1)
		/sizeof(asn_DEF_RRCConnectionReconfiguration_v1310_IEs_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RRCConnectionReconfiguration_v1310_IEs_1,
	6,	/* Elements count */
	&asn_SPC_RRCConnectionReconfiguration_v1310_IEs_specs_1	/* Additional specs */
};

