/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#include "SRS-ConfigAp-r13.h"

static int
srs_BandwidthAp_r13_3_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
srs_BandwidthAp_r13_3_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
srs_BandwidthAp_r13_3_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
srs_BandwidthAp_r13_3_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
srs_BandwidthAp_r13_3_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
srs_BandwidthAp_r13_3_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
srs_BandwidthAp_r13_3_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
srs_BandwidthAp_r13_3_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
srs_BandwidthAp_r13_3_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	srs_BandwidthAp_r13_3_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
cyclicShiftAp_r13_10_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
cyclicShiftAp_r13_10_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
cyclicShiftAp_r13_10_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
cyclicShiftAp_r13_10_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
cyclicShiftAp_r13_10_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
cyclicShiftAp_r13_10_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
cyclicShiftAp_r13_10_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
cyclicShiftAp_r13_10_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
cyclicShiftAp_r13_10_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
cyclicShiftAp_r13_10_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	cyclicShiftAp_r13_10_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
transmissionCombNum_r13_23_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
transmissionCombNum_r13_23_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
transmissionCombNum_r13_23_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
transmissionCombNum_r13_23_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
transmissionCombNum_r13_23_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
transmissionCombNum_r13_23_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
transmissionCombNum_r13_23_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
transmissionCombNum_r13_23_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
transmissionCombNum_r13_23_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
transmissionCombNum_r13_23_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	transmissionCombNum_r13_23_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_freqDomainPositionAp_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 23)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_transmissionCombAp_r13_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_srs_BandwidthAp_r13_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_cyclicShiftAp_r13_constr_10 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  11 }	/* (0..11) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_transmissionCombNum_r13_constr_23 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_freqDomainPositionAp_r13_constr_8 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  23 }	/* (0..23) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_transmissionCombAp_r13_constr_9 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_srs_BandwidthAp_r13_value2enum_3[] = {
	{ 0,	3,	"bw0" },
	{ 1,	3,	"bw1" },
	{ 2,	3,	"bw2" },
	{ 3,	3,	"bw3" }
};
static unsigned int asn_MAP_srs_BandwidthAp_r13_enum2value_3[] = {
	0,	/* bw0(0) */
	1,	/* bw1(1) */
	2,	/* bw2(2) */
	3	/* bw3(3) */
};
static asn_INTEGER_specifics_t asn_SPC_srs_BandwidthAp_r13_specs_3 = {
	asn_MAP_srs_BandwidthAp_r13_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_srs_BandwidthAp_r13_enum2value_3,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_srs_BandwidthAp_r13_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_srs_BandwidthAp_r13_3 = {
	"srs-BandwidthAp-r13",
	"srs-BandwidthAp-r13",
	srs_BandwidthAp_r13_3_free,
	srs_BandwidthAp_r13_3_print,
	srs_BandwidthAp_r13_3_constraint,
	srs_BandwidthAp_r13_3_decode_ber,
	srs_BandwidthAp_r13_3_encode_der,
	srs_BandwidthAp_r13_3_decode_xer,
	srs_BandwidthAp_r13_3_encode_xer,
	srs_BandwidthAp_r13_3_decode_uper,
	srs_BandwidthAp_r13_3_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_srs_BandwidthAp_r13_tags_3,
	sizeof(asn_DEF_srs_BandwidthAp_r13_tags_3)
		/sizeof(asn_DEF_srs_BandwidthAp_r13_tags_3[0]) - 1, /* 1 */
	asn_DEF_srs_BandwidthAp_r13_tags_3,	/* Same as above */
	sizeof(asn_DEF_srs_BandwidthAp_r13_tags_3)
		/sizeof(asn_DEF_srs_BandwidthAp_r13_tags_3[0]), /* 2 */
	&asn_PER_type_srs_BandwidthAp_r13_constr_3,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_srs_BandwidthAp_r13_specs_3	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_cyclicShiftAp_r13_value2enum_10[] = {
	{ 0,	3,	"cs0" },
	{ 1,	3,	"cs1" },
	{ 2,	3,	"cs2" },
	{ 3,	3,	"cs3" },
	{ 4,	3,	"cs4" },
	{ 5,	3,	"cs5" },
	{ 6,	3,	"cs6" },
	{ 7,	3,	"cs7" },
	{ 8,	3,	"cs8" },
	{ 9,	3,	"cs9" },
	{ 10,	4,	"cs10" },
	{ 11,	4,	"cs11" }
};
static unsigned int asn_MAP_cyclicShiftAp_r13_enum2value_10[] = {
	0,	/* cs0(0) */
	1,	/* cs1(1) */
	10,	/* cs10(10) */
	11,	/* cs11(11) */
	2,	/* cs2(2) */
	3,	/* cs3(3) */
	4,	/* cs4(4) */
	5,	/* cs5(5) */
	6,	/* cs6(6) */
	7,	/* cs7(7) */
	8,	/* cs8(8) */
	9	/* cs9(9) */
};
static asn_INTEGER_specifics_t asn_SPC_cyclicShiftAp_r13_specs_10 = {
	asn_MAP_cyclicShiftAp_r13_value2enum_10,	/* "tag" => N; sorted by tag */
	asn_MAP_cyclicShiftAp_r13_enum2value_10,	/* N => "tag"; sorted by N */
	12,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_cyclicShiftAp_r13_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cyclicShiftAp_r13_10 = {
	"cyclicShiftAp-r13",
	"cyclicShiftAp-r13",
	cyclicShiftAp_r13_10_free,
	cyclicShiftAp_r13_10_print,
	cyclicShiftAp_r13_10_constraint,
	cyclicShiftAp_r13_10_decode_ber,
	cyclicShiftAp_r13_10_encode_der,
	cyclicShiftAp_r13_10_decode_xer,
	cyclicShiftAp_r13_10_encode_xer,
	cyclicShiftAp_r13_10_decode_uper,
	cyclicShiftAp_r13_10_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_cyclicShiftAp_r13_tags_10,
	sizeof(asn_DEF_cyclicShiftAp_r13_tags_10)
		/sizeof(asn_DEF_cyclicShiftAp_r13_tags_10[0]) - 1, /* 1 */
	asn_DEF_cyclicShiftAp_r13_tags_10,	/* Same as above */
	sizeof(asn_DEF_cyclicShiftAp_r13_tags_10)
		/sizeof(asn_DEF_cyclicShiftAp_r13_tags_10[0]), /* 2 */
	&asn_PER_type_cyclicShiftAp_r13_constr_10,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_cyclicShiftAp_r13_specs_10	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_transmissionCombNum_r13_value2enum_23[] = {
	{ 0,	2,	"n2" },
	{ 1,	2,	"n4" }
};
static unsigned int asn_MAP_transmissionCombNum_r13_enum2value_23[] = {
	0,	/* n2(0) */
	1	/* n4(1) */
};
static asn_INTEGER_specifics_t asn_SPC_transmissionCombNum_r13_specs_23 = {
	asn_MAP_transmissionCombNum_r13_value2enum_23,	/* "tag" => N; sorted by tag */
	asn_MAP_transmissionCombNum_r13_enum2value_23,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_transmissionCombNum_r13_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transmissionCombNum_r13_23 = {
	"transmissionCombNum-r13",
	"transmissionCombNum-r13",
	transmissionCombNum_r13_23_free,
	transmissionCombNum_r13_23_print,
	transmissionCombNum_r13_23_constraint,
	transmissionCombNum_r13_23_decode_ber,
	transmissionCombNum_r13_23_encode_der,
	transmissionCombNum_r13_23_decode_xer,
	transmissionCombNum_r13_23_encode_xer,
	transmissionCombNum_r13_23_decode_uper,
	transmissionCombNum_r13_23_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_transmissionCombNum_r13_tags_23,
	sizeof(asn_DEF_transmissionCombNum_r13_tags_23)
		/sizeof(asn_DEF_transmissionCombNum_r13_tags_23[0]) - 1, /* 1 */
	asn_DEF_transmissionCombNum_r13_tags_23,	/* Same as above */
	sizeof(asn_DEF_transmissionCombNum_r13_tags_23)
		/sizeof(asn_DEF_transmissionCombNum_r13_tags_23[0]), /* 2 */
	&asn_PER_type_transmissionCombNum_r13_constr_23,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_transmissionCombNum_r13_specs_23	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SRS_ConfigAp_r13_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_ConfigAp_r13, srs_AntennaPortAp_r13),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SRS_AntennaPort,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"srs-AntennaPortAp-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_ConfigAp_r13, srs_BandwidthAp_r13),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_srs_BandwidthAp_r13_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"srs-BandwidthAp-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_ConfigAp_r13, freqDomainPositionAp_r13),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_freqDomainPositionAp_r13_constraint_1,
		&asn_PER_memb_freqDomainPositionAp_r13_constr_8,
		0,
		"freqDomainPositionAp-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_ConfigAp_r13, transmissionCombAp_r13),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_transmissionCombAp_r13_constraint_1,
		&asn_PER_memb_transmissionCombAp_r13_constr_9,
		0,
		"transmissionCombAp-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_ConfigAp_r13, cyclicShiftAp_r13),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_cyclicShiftAp_r13_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cyclicShiftAp-r13"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SRS_ConfigAp_r13, transmissionCombNum_r13),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_transmissionCombNum_r13_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"transmissionCombNum-r13"
		},
};
static ber_tlv_tag_t asn_DEF_SRS_ConfigAp_r13_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SRS_ConfigAp_r13_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* srs-AntennaPortAp-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* srs-BandwidthAp-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* freqDomainPositionAp-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* transmissionCombAp-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* cyclicShiftAp-r13 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* transmissionCombNum-r13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_SRS_ConfigAp_r13_specs_1 = {
	sizeof(struct SRS_ConfigAp_r13),
	offsetof(struct SRS_ConfigAp_r13, _asn_ctx),
	asn_MAP_SRS_ConfigAp_r13_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SRS_ConfigAp_r13 = {
	"SRS-ConfigAp-r13",
	"SRS-ConfigAp-r13",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SRS_ConfigAp_r13_tags_1,
	sizeof(asn_DEF_SRS_ConfigAp_r13_tags_1)
		/sizeof(asn_DEF_SRS_ConfigAp_r13_tags_1[0]), /* 1 */
	asn_DEF_SRS_ConfigAp_r13_tags_1,	/* Same as above */
	sizeof(asn_DEF_SRS_ConfigAp_r13_tags_1)
		/sizeof(asn_DEF_SRS_ConfigAp_r13_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SRS_ConfigAp_r13_1,
	6,	/* Elements count */
	&asn_SPC_SRS_ConfigAp_r13_specs_1	/* Additional specs */
};

