/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_UL_CyclicPrefixLength_H_
#define	_UL_CyclicPrefixLength_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_CyclicPrefixLength {
	UL_CyclicPrefixLength_len1	= 0,
	UL_CyclicPrefixLength_len2	= 1
} e_UL_CyclicPrefixLength;

/* UL-CyclicPrefixLength */
typedef ENUMERATED_t	 UL_CyclicPrefixLength_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_CyclicPrefixLength;
asn_struct_free_f UL_CyclicPrefixLength_free;
asn_struct_print_f UL_CyclicPrefixLength_print;
asn_constr_check_f UL_CyclicPrefixLength_constraint;
ber_type_decoder_f UL_CyclicPrefixLength_decode_ber;
der_type_encoder_f UL_CyclicPrefixLength_encode_der;
xer_type_decoder_f UL_CyclicPrefixLength_decode_xer;
xer_type_encoder_f UL_CyclicPrefixLength_encode_xer;
per_type_decoder_f UL_CyclicPrefixLength_decode_uper;
per_type_encoder_f UL_CyclicPrefixLength_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_CyclicPrefixLength_H_ */
#include <asn_internal.h>
