/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_VarRLF_Report_r10_H_
#define	_VarRLF_Report_r10_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RLF-Report-r9.h"
#include "PLMN-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VarRLF-Report-r10 */
typedef struct VarRLF_Report_r10 {
	RLF_Report_r9_t	 rlf_Report_r10;
	PLMN_Identity_t	 plmn_Identity_r10;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarRLF_Report_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VarRLF_Report_r10;

#ifdef __cplusplus
}
#endif

#endif	/* _VarRLF_Report_r10_H_ */
#include <asn_internal.h>
