/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "/home/qiongbod/asn1c-0.9.27/asn1c/input/36331-d10.asn"
 * 	`asn1c -S /home/qiongbod/asn1c-0.9.27/skeletons -fcompound-names -fwide-types -gen-PER`
 */

#ifndef	_VictimSystemType_r11_H_
#define	_VictimSystemType_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include <ENUMERATED.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VictimSystemType_r11__gps_r11 {
	VictimSystemType_r11__gps_r11_true	= 0
} e_VictimSystemType_r11__gps_r11;
typedef enum VictimSystemType_r11__glonass_r11 {
	VictimSystemType_r11__glonass_r11_true	= 0
} e_VictimSystemType_r11__glonass_r11;
typedef enum VictimSystemType_r11__bds_r11 {
	VictimSystemType_r11__bds_r11_true	= 0
} e_VictimSystemType_r11__bds_r11;
typedef enum VictimSystemType_r11__galileo_r11 {
	VictimSystemType_r11__galileo_r11_true	= 0
} e_VictimSystemType_r11__galileo_r11;
typedef enum VictimSystemType_r11__wlan_r11 {
	VictimSystemType_r11__wlan_r11_true	= 0
} e_VictimSystemType_r11__wlan_r11;
typedef enum VictimSystemType_r11__bluetooth_r11 {
	VictimSystemType_r11__bluetooth_r11_true	= 0
} e_VictimSystemType_r11__bluetooth_r11;

/* VictimSystemType-r11 */
typedef struct VictimSystemType_r11 {
	ENUMERATED_t	*gps_r11	/* OPTIONAL */;
	ENUMERATED_t	*glonass_r11	/* OPTIONAL */;
	ENUMERATED_t	*bds_r11	/* OPTIONAL */;
	ENUMERATED_t	*galileo_r11	/* OPTIONAL */;
	ENUMERATED_t	*wlan_r11	/* OPTIONAL */;
	ENUMERATED_t	*bluetooth_r11	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VictimSystemType_r11_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_gps_r11_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_glonass_r11_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_bds_r11_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_galileo_r11_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_wlan_r11_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_bluetooth_r11_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_VictimSystemType_r11;

#ifdef __cplusplus
}
#endif

#endif	/* _VictimSystemType_r11_H_ */
#include <asn_internal.h>
